# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: test-app_development
  username: root
  password: "123"

test:
  adapter: mysql2 
  database: test-app-test
  username: root
  password: "123"

production:
  adapter: mysql2 
  database: test-app-production
  username: root
  password: "123"
